In [34]:

# 做完特徵工程前的所有準備
import pandas as pd
import numpy as np
import datetime
from sklearn.preprocessing import MinMaxScaler
from sklearn.model_selection import cross_val_score

from sklearn import datasets, metrics
from sklearn.model_selection import train_test_split
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import mean_squared_error, r2_score

In [65]:
#匯入資料
data_path = 'data-science-london-scikit-learn/'
df_train = pd.read_csv(data_path + 'train.csv', header=None)
df_test = pd.read_csv(data_path + 'test.csv', header=None)
df_trainLabels = pd.read_csv(data_path + 'trainLabels.csv', header=None,names=['class'])

In [66]:
print(df_train.shape)
print(df_test.shape)

(1000, 40)
(9000, 40)

In [67]:
df_trainLabels

     class
0        1
1        0
2        0
3        1
4        0
5        1
6        0
7        1
8        1
9        0
10       1
11       0
12       0
13       0
14       0
15       1
16       1
17       0
18       1
19       0
20       1
21       0
22       0
23       1
24       0
25       1
26       1
27       1
28       0
29       1
..     ...
970      1
971      0
972      1
973      1
974      1
975      1
976      0
977      0
978      0
979      0
980      0
981      1
982      1
983      0
984      0
985      0
986      0
987      0
988      1
989      0
990      1
991      1
992      1
993      1
994      0
995      0
996      1
997      1
998      0
999      0

[1000 rows x 1 columns]

In [68]:
#二元分類
print( df_trainLabels['class'].nunique() )
print(np.sum(df_trainLabels['class'] ==1 ))
print(np.sum(df_trainLabels['class'] ==0 ))

2
510
490

In [69]:
# 切分訓練集/測試集
x_train, x_test, y_train, y_test = train_test_split(df_train, df_trainLabels, test_size=0.25, random_state=4)

In [70]:
# 建立模型
clf = DecisionTreeClassifier()

# 訓練模型
clf.fit(x_train, y_train)

# 預測測試集
y_pred = clf.predict(x_test)


acc = metrics.accuracy_score(y_test, y_pred)
print("Accuracy: ", acc)
#print("Feature importance: ", clf.feature_importances_)

Accuracy:  0.796

In [39]:
#GradientBoosting
# 建立模型
GBclf = GradientBoostingClassifier(n_estimators=100)

# 訓練模型
GBclf.fit(x_train, y_train)

# 預測測試集
y_pred = GBclf.predict(x_test)


acc = metrics.accuracy_score(y_test, y_pred)
print("Accuracy: ", acc)

C:\Users\user\Anaconda3\lib\site-packages\sklearn\ensemble\gradient_boosting.py:1450: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

Accuracy:  0.848

In [98]:
submit = GBclf.predict(df_test)

In [99]:
index = [i for i in range(1, len(submit)+1)]
submit = pd.DataFrame({'Solution': submit})
submit['Id'] = np.arange(1,submit.shape[0]+1)
submit = submit[['Id','Solution']]

In [101]:
submit.to_csv('london.csv', index = False)